### PR TITLE
#38 Links in entries about recently added blogs were pointing to the …

### PR DESCRIPTION
**Pull request by michalkarolik**
…rss feed, not to the blog main pages - fixed.

Ive moved bloggers.json file to src/main/resources so its available in test files. It was read from github for all environments, so Ive used Resource abstraction instead URL - bloggers.json is now taken from project sources for dev env.

### CODE REVIEW

**Comment by tdziurko** [comment]
Ok, generally it's hard to discuss about PR if you included two complete separate things in it :)

But...
1. Main purpose of putting bloggers.json in project root was to make it easily "discoerable" and easy to find when opening project page. But maybe I am overestimating importance of its location... WDYT?

2. Adding link to the main page to json is redundant as it could be extracted from RSS (SyndFeed link or URI properties), so maybe we should base on this and populate DB records from that source of data? Again WDYT? :)

**Comment by michalkarolik** [comment]
1. I dont think path of a file is that important - users probably use link in README anyway.

2. Do you mean its possible to fetch main blog url by rss link in all cases? 
  "http://michalplachta.com/feed"   ->   "http://michalplachta.com/"
  "https://medium.com/feed/@kubukoz" -> "https://medium.com/@kubukoz/"
  "http://www.pietrzak.me/feeds/posts/default"-> "http://www.pietrzak.me/"
  "http://zuchos.com/atom.xml" -> "http://zuchos.com/"
  "http://luksza.org/feed/atom/" -> "http://luksza.org/"
  "http://bialon.net//index.xml" -> "http://bialon.net/"
 etc
 I wasnt aware of SyndFeed class, if it can convert all above cases we may consider it. Current solution is at least clear :)

**Comment by tdziurko** [comment]
1. Agreed :)
2. Yeah, I've double checked that yesterday for first few blogs using debugger in RssFetchingActor. As far as I've read in the documentation, it's the part of RSS/Atom standard. Your solution is clearer, but is very manual :)

Details of getLink() method:
https://github.com/rometools/rome/blob/master/src/main/java/com/rometools/rome/feed/synd/SyndFeed.java#L223

**Comment by tdziurko** [comment]
Please remember to put those changes in two seperate PRs so they could be merged independently :)

**Pull request closed without merging**
