### PR TITLE
Added another blog

### PR DESCRIPTION
**Pull request by spacanowski**

### CODE REVIEW

**Comment by tdziurko** [comment]
Can we change spc to more meaningful name? :)

**Comment by spacanowski** [comment]
Done

**Comment by tdziurko** [comment]
I prefer full names but it's your choice :)

**Comment by krasinski** [comment]
This rss feed serves relative links - they are not working when clicked from newsletter.
Example:
```xml
<link>
/java/patterns/2015/09/16/patterns-revisited-factory/
</link>
<guid isPermaLink="true">
/java/patterns/2015/09/16/patterns-revisited-factory/
</guid>
```
@spacanowski You should probably fix it.

**Comment by tdziurko** [comment]
I've noticed it today too :) Already sent an e-mail to Szymon.

On 5 November 2015 at 00:51, Bartosz Krasiński <notifications@github.com>
wrote:

> This rss feed serves relative links - they are not working when clicked
> from newsletter.
> Example:
>
> <link>
> /java/patterns/2015/09/16/patterns-revisited-factory/
> </link>
> <guid isPermaLink="true">
> /java/patterns/2015/09/16/patterns-revisited-factory/
> </guid>
>
> @spacanowski <https://github.com/spacanowski> You should probably fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tdziurko/jvm-bloggers/pull/49#issuecomment-153907777>.
>



-- 
Regards / Pozdrawiam,
Tomek Dziurko
http://tomaszdziurko.pl

**Comment by spacanowski** [comment]
Fixed

**Pull request merged**
