### PR TITLE
Issue 112 introduce common formatting, closes #112

### LINKED ISSUE #112: Introduce common formatting rules to minimise reformatting diffs in pull requests

### PR DESCRIPTION
**Pull request by tdziurko**
This is a WIP towards common formatting rules.

1. New checkstyle based on Google Java Style Guide 

Changes there (as in commits in this PR):
 - Raise errors when checkstyle fails
 - Classes from google.com are no longer treated in a special way in import ordering
 - Indentation is based on 4-spaces (Google currently advices 2-spaces base indentation)
 - Javadocs are not required

There are two Eclipse/IntelliJ formatters that are currently almost in line with checkstyle checks. They will requires some tuning (especially indentation and import ordering) but we need to agree on the checkstyle file first.
 
Things that I want to discuss (taken from failing checkstyle report):
1. If you have any comments to the changes already applied to the original checkstyle file, please write them in this topic.
2. `Line is longer than 100 characters (found 113). [LineLength]` - is 100 a good number? I have a feeling that it is a bit too low :)
3. `'.' should be on a new line. [SeparatorWrap]`:

        authFeature = HttpAuthenticationFeature.
            basicBuilder().
            nonPreemptive().
            credentials("api", malingApiKey).
            build();
Do we have any preferences here? `.` on a new line looks reasonable fix to this code. 
4. `Package name 'pl.tomaszdziurko.jvm_bloggers.blog_posts' must match pattern '^[a-z]+(\.[a-z][a-z0-9]*)*$'. [PackageName]` - I would like to allow `_` in package names as they are more readable than `blogposts` What do you think?
5. There is still a problem in breaking lines strategy. But it will be hard to standarise I think.

If you spot anything else in checkstyle.xml, please also raise it here.

### CODE REVIEW

**Comment by goostleek** [comment]
>2. Line is longer than 100 characters (found 113). [LineLength] - is 100 a good number? I have a feeling that it is a bit too low :)

I'm using 160 (2 * 80) and it seems to be ok :)
> '.' should be on a new line. [SeparatorWrap]:

It seems ok. Having it on new line brings extra advantage, when you type a `.` (dot) on new line you will instantly get code completion proposal in right place:
```
authFeature = HttpAuthenticationFeature
        .ba[code completion proposals here]()
        .[another completion proposal]()
```

**Comment by delor** [comment]
For quite some time I format my code by hand (call me crazy). In most project I participated in checkstyle became nuisance.

As general rule I try to keep line length as short as possible but from time to time there's that long line that look good being just one line but unfortunately it breaks checkstyle rule so you have to change it artificially just to adhere to some silly rule. Thats why I think we sould not have line limit.

As for line breaks I'm happy as long as formatter won't change split or join lines by some magical algorithm in the end lowering readability of code.

These days I have only one rule for code formatting: "the line can appear as changed in diff only when that change is related to task you are working on and it's logical change" so that there is no "oh, I have changed that line because I or my formatter didn't like how it looked". The rest is handled through code review process.

**Comment by cslysy** [comment]
Re: 2. I would even say that 80 is better but we can stay with 100. Such a code is easier to: watch on mobile devices, compare in split screen diff tool, show on presentations, attach in books. Please remember that formatting depends of file type. For instance, XML (HTML especially) is like designed to deeply nesting so I think that character limitation rule should not affect that files at all.
Re: 3. Correct, lines should not ends with .
Re: 4. I would prefer package name without underscores

**Comment by tdziurko** [comment]
* Maybe let's try this 100 chars suggested by Google and after a month we will see if this rule is doing more harm than good?
* I am reluctant to refactor whole application to get rid of dashes in package names.

**Comment by cslysy** [comment]
> I am reluctant to refactor whole application only to get rid of dashes in package names

That's fine, it is only my personal preferece :smile:

Unfortunately, I didn't have time to test test the formater on real code yet. Hope I dive into this today.

**Comment by tdziurko** [comment]
I can tweak intellij formatter, but someone (probably @goostleek or someone else using Eclipse) needs to check formatter for this IDE.

**Comment by goostleek** [comment]
Ok I will prepare the formatter for Eclipse then.

**Comment by goostleek** [comment]
We forgot to decide which EOF to use, _Windows_ or _Unix_ style one? Personally I prefer Unix (LF only). WDYT?

**Comment by delor** [comment]
@goostleek that should be handled by git

**Comment by tdziurko** [comment]
But you have to actually store one of them in the repo. AFAIK Git configures how your local repo works.

**Comment by delor** [comment]
Do you set that somehow? I have never had to do that so I was probably using default.

**Comment by goostleek** [comment]
It's controlled by `core.autocrlf` _.gitconfig_ entry and determines EOLs of the files checked out into your local workspace only. It does not determine EOLs of files that you checked in into the repo. In other words we should still have a standard enforced by formatters and checkstyle.

**Pull request merged**
